# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('excel_file', models.FileField(blank=True, upload_to='files')),
            ],
        ),
    ]
